// ============================================================
// MOCK DATA — CampusBet
// Used as fallback until backend is ready
// ============================================================

export const GAMES = [
  'Super Smash Bros',
  'Mario Kart',
  'FIFA / EA FC',
  'Chess',
  'Valorant',
  'BGMI / PUBG Mobile',
  'Carrom',
  'Table Tennis',
  'Custom',
];

export const MOCK_USERS = [
  {
    _id: 'u1',
    name: 'Arjun Sharma',
    email: 'arjun@college.edu.in',
    college: 'IIT Delhi',
    role: 'player',
    credits: 1450,
    stats: { matchesPlayed: 34, matchesWon: 22, tournamentsPlayed: 5, tournamentsWon: 2 },
    badges: ['Campus Champion', 'Valorant Pro'],
    avatarUrl: null,
    rank: 1,
  },
  {
    _id: 'u2',
    name: 'Priya Nair',
    email: 'priya@college.edu.in',
    college: 'NIT Trichy',
    role: 'player',
    credits: 980,
    stats: { matchesPlayed: 28, matchesWon: 18, tournamentsPlayed: 4, tournamentsWon: 1 },
    badges: ['Chess Master'],
    avatarUrl: null,
    rank: 2,
  },
  {
    _id: 'u3',
    name: 'Rohan Mehta',
    email: 'rohan@college.edu.in',
    college: 'BITS Pilani',
    role: 'host',
    credits: 2200,
    stats: { matchesPlayed: 50, matchesWon: 35, tournamentsPlayed: 8, tournamentsWon: 3 },
    badges: ['Veteran', 'Tournament Host'],
    avatarUrl: null,
    rank: 3,
  },
  {
    _id: 'u4',
    name: 'Sneha Patel',
    email: 'sneha@college.edu.in',
    college: 'VIT Vellore',
    role: 'player',
    credits: 760,
    stats: { matchesPlayed: 20, matchesWon: 12, tournamentsPlayed: 3, tournamentsWon: 0 },
    badges: [],
    avatarUrl: null,
    rank: 4,
  },
  {
    _id: 'u5',
    name: 'Dev Anand',
    email: 'dev@college.edu.in',
    college: 'IIT Bombay',
    role: 'host',
    credits: 3100,
    stats: { matchesPlayed: 60, matchesWon: 42, tournamentsPlayed: 10, tournamentsWon: 4 },
    badges: ['Legend', 'BGMI King'],
    avatarUrl: null,
    rank: 5,
  },
];

export const CURRENT_USER = {
  _id: 'me1',
  name: 'You (Demo)',
  email: 'demo@college.edu.in',
  college: 'Demo University',
  role: 'player',
  credits: 500,
  stats: { matchesPlayed: 10, matchesWon: 6, tournamentsPlayed: 2, tournamentsWon: 0 },
  badges: ['Newcomer'],
  avatarUrl: null,
  rank: 42,
};

// ─── Lobbies ────────────────────────────────────────────────
export const MOCK_LOBBIES = [
  {
    _id: 'l1',
    title: 'Valorant 1v1 — Clutch Kings',
    game: 'Valorant',
    hostId: 'u3',
    host: MOCK_USERS[2],
    college: 'BITS Pilani',
    bidAmount: 100,
    maxPlayers: 2,
    currentPlayers: ['u3'],
    status: 'open',
    description: 'Best of 3, Pistol round only. Bring your A-game.',
    scheduledAt: new Date(Date.now() + 3600000).toISOString(), // 1hr from now
    createdAt: new Date(Date.now() - 600000).toISOString(),
    spectatorBids: [
      { userId: 'u1', onPlayer: 'u3', amount: 50 },
    ],
  },
  {
    _id: 'l2',
    title: 'Chess Blitz — Speed Thinkers',
    game: 'Chess',
    hostId: 'u1',
    host: MOCK_USERS[0],
    college: 'IIT Delhi',
    bidAmount: 200,
    maxPlayers: 2,
    currentPlayers: ['u1', 'u2'],
    status: 'in-progress',
    description: '5-minute blitz. No takebacks.',
    scheduledAt: new Date(Date.now() - 1800000).toISOString(), // started 30 min ago
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    spectatorBids: [
      { userId: 'u4', onPlayer: 'u1', amount: 100 },
      { userId: 'u5', onPlayer: 'u2', amount: 75 },
    ],
  },
  {
    _id: 'l3',
    title: 'FIFA 25 — Weekend Warrior',
    game: 'FIFA / EA FC',
    hostId: 'u5',
    host: MOCK_USERS[4],
    college: 'IIT Bombay',
    bidAmount: 150,
    maxPlayers: 2,
    currentPlayers: ['u5'],
    status: 'open',
    description: '2 halves × 6 mins. No custom tactics.',
    scheduledAt: new Date(Date.now() + 7200000).toISOString(),
    createdAt: new Date(Date.now() - 300000).toISOString(),
    spectatorBids: [],
  },
  {
    _id: 'l4',
    title: 'BGMI Squad — Campus Royale',
    game: 'BGMI / PUBG Mobile',
    hostId: 'u2',
    host: MOCK_USERS[1],
    college: 'NIT Trichy',
    bidAmount: 300,
    maxPlayers: 4,
    currentPlayers: ['u2', 'u4'],
    status: 'open',
    description: 'Squad game. Each squad member places 300 credits. Winner takes all.',
    scheduledAt: new Date(Date.now() + 10800000).toISOString(),
    createdAt: new Date(Date.now() - 1200000).toISOString(),
    spectatorBids: [],
  },
  {
    _id: 'l5',
    title: 'Smash Bros — Smackdown Sunday',
    game: 'Super Smash Bros',
    hostId: 'u3',
    host: MOCK_USERS[2],
    college: 'BITS Pilani',
    bidAmount: 75,
    maxPlayers: 2,
    currentPlayers: ['u3', 'u1'],
    status: 'completed',
    description: 'Stock match. 3 stocks each.',
    scheduledAt: new Date(Date.now() - 86400000).toISOString(),
    createdAt: new Date(Date.now() - 90000000).toISOString(),
    spectatorBids: [
      { userId: 'u5', onPlayer: 'u1', amount: 50 },
    ],
    winnerId: 'u1',
  },
  {
    _id: 'l6',
    title: 'Mario Kart — Rainbow Road Roulette',
    game: 'Mario Kart',
    hostId: 'u4',
    host: MOCK_USERS[3],
    college: 'VIT Vellore',
    bidAmount: 50,
    maxPlayers: 4,
    currentPlayers: ['u4'],
    status: 'open',
    description: 'Random track selection every race. 3 races total.',
    scheduledAt: new Date(Date.now() + 5400000).toISOString(),
    createdAt: new Date(Date.now() - 900000).toISOString(),
    spectatorBids: [],
  },
];

// ─── Tournaments ─────────────────────────────────────────────
export const MOCK_TOURNAMENTS = [
  {
    _id: 't1',
    title: 'Campus Valorant Open 2025',
    game: 'Valorant',
    format: 'single-elim',
    hostId: 'u5',
    host: MOCK_USERS[4],
    college: 'IIT Bombay',
    maxParticipants: 16,
    participants: ['u1', 'u2', 'u3', 'u4', 'u5'],
    entryCredits: 200,
    prizePool: 3200,
    status: 'upcoming',
    startDate: new Date(Date.now() + 86400000 * 3).toISOString(),
    endDate: new Date(Date.now() + 86400000 * 5).toISOString(),
    rules: 'Standard Valorant rules. No smurfing. Result screenshots mandatory.',
    bracket: null,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    _id: 't2',
    title: 'Chess Championship — Winter Cup',
    game: 'Chess',
    format: 'round-robin',
    hostId: 'u3',
    host: MOCK_USERS[2],
    college: 'BITS Pilani',
    maxParticipants: 8,
    participants: ['u1', 'u2', 'u3', 'u4', 'u5'],
    entryCredits: 100,
    prizePool: 800,
    status: 'live',
    startDate: new Date(Date.now() - 3600000).toISOString(),
    endDate: new Date(Date.now() + 86400000 * 2).toISOString(),
    rules: '10+0 time control. FIDE rules apply.',
    bracket: null,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    _id: 't3',
    title: 'BGMI Invitational — Squad Wars',
    game: 'BGMI / PUBG Mobile',
    format: 'single-elim',
    hostId: 'u1',
    host: MOCK_USERS[0],
    college: 'IIT Delhi',
    maxParticipants: 32,
    participants: Array.from({ length: 18 }, (_, i) => `u${i + 1}`),
    entryCredits: 500,
    prizePool: 9000,
    status: 'completed',
    startDate: new Date(Date.now() - 86400000 * 10).toISOString(),
    endDate: new Date(Date.now() - 86400000 * 8).toISOString(),
    rules: 'TPP mode. Squad of 4. No emulators.',
    bracket: null,
    winnerId: 'u5',
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
  },
];

// ─── Match history for current user ─────────────────────────
export const MOCK_MY_MATCHES = [
  {
    _id: 'm1',
    lobbyId: 'l5',
    game: 'Super Smash Bros',
    opponent: MOCK_USERS[2],
    result: 'won',
    creditsChange: +75,
    date: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    _id: 'm2',
    lobbyId: 'l2',
    game: 'Chess',
    opponent: MOCK_USERS[0],
    result: 'lost',
    creditsChange: -200,
    date: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    _id: 'm3',
    lobbyId: 'l6',
    game: 'Mario Kart',
    opponent: MOCK_USERS[3],
    result: 'won',
    creditsChange: +50,
    date: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
];

// ─── Leaderboard ─────────────────────────────────────────────
export const MOCK_LEADERBOARD = MOCK_USERS.map((u, i) => ({
  ...u,
  rank: i + 1,
  winRate: Math.round((u.stats.matchesWon / u.stats.matchesPlayed) * 100),
})).sort((a, b) => b.stats.matchesWon - a.stats.matchesWon);
